#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

REPO_URL=https://github.com/Wignesh/.dotfiles.git
REPO_PATH="$HOME/.dotfiles"

reset_color=$(tput sgr 0)

info() {
    printf "%s[*] %s%s\n" "$(tput setaf 4)" "$1" "$reset_color"
}

success() {
    printf "%s[*] %s%s\n" "$(tput setaf 2)" "$1" "$reset_color"
}

err() {
    printf "%s[*] %s%s\n" "$(tput setaf 1)" "$1" "$reset_color"
}

warn() {
    printf "%s[*] %s%s\n" "$(tput setaf 3)" "$1" "$reset_color"
}

install_xcode() {
    if xcode-select -p > /dev/null; then
        warn "xCode Command Line Tools already installed"
    else
        info "Installing xCode Command Line Tools..."
        xcode-select --install
        sudo xcodebuild -license accept
    fi
}

install_homebrew() {
    export HOMEBREW_CASK_OPTS="--appdir=/Applications"
    if hash brew &>/dev/null; then
        warn "Homebrew already installed"
    else
        info "Installing homebrew..."
        sudo --validate  # reset `sudo` timeout to use Homebrew install in noninteractive mode
        CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
}

install_oh_my_zsh() {
    if [[ ! -f ~/.zshrc ]]; then
        info "Installing oh my zsh..."
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
        
        chmod 744 ~/.oh-my-zsh/oh-my-zsh.sh
        
        info "Installing powerlevel10k"
        git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
        git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
        git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
    else
        warn "oh-my-zsh already installed"
    fi
}

stow_dotfiles() {

    local files=(
        ".gitconfig"
        ".zshrc"
        ".p10k.sh"
        ".config/iterm2/com.googlecode.iterm2.plist"
    )

    info "Removing existing config files"

    for f in $files; do
        rm -rf "$HOME/$f"
    done

    local dotfiles="git iterm2 zsh"

    stow -d ~/.dotfiles/.dots --verbose 1 -t ~/ $dotfiles

}

info "Bootstraping..."

install_xcode
install_homebrew

info "Cloning .dotfiles repo from $REPO_URL into $REPO_PATH"
git clone "$REPO_URL" "$REPO_PATH"

info "Change path to $REPO_PATH"
cd "$REPO_PATH" >/dev/null

info "======= Homebrew packages ======="
sudo -v
brew bundle --file=~/.dotfiles/Brewfile
success "Finished installing Homebrew packages"

info "Installing nvm..."

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

info "Installing aws cli..."

curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"

sudo installer -pkg AWSCLIV2.pkg -target /

aws --version

rm AWSCLIV2.pkg || true

info "======= Configuration ======="
stow_dotfiles

success "Finished stowing dotfiles"

success "Done"

info "System needs to restart. Restart?"

select yn in "y" "n"; do
    case $yn in
        y ) sudo shutdown -r now; break;;
        n ) exit;;
    esac
done